using Microsoft.VisualStudio.TestTools.UnitTesting;
using QuantityMeasurement.Models.DTOs;
using QuantityMeasurement.Models.Entities;
using QuantityMeasurement.Models.Exceptions;
using QuantityMeasurement.Repository.Service;
using QuantityMeasurement.Repository.Interfaces;
using QuantityMeasurement.Service.Service;
using QuantityMeasurement.Service.Interfaces;

namespace QuantityMeasurementApp.Tests
{
    [TestClass]
    [DoNotParallelize]
    public class UC15tests
    {
        // ─── Fields ───────────────────────────────────────────

        private IQuantityMeasurementRepository _repository = null!;
        private IQuantityMeasurementService    _service    = null!;

        // ─── Setup ────────────────────────────────────────────

        [TestInitialize]
        public void Setup()
        {
            _repository = QuantityMeasurementCacheRepository.GetInstance();
            _repository.ClearAll();
            _service    = new QuantityMeasurementServiceImpl(_repository);
        }

        // ─── Cleanup ──────────────────────────────────────────

        [TestCleanup]
        public void Cleanup()
        {
            _repository.ClearAll();
        }

        // ═════════════════════════════════════════════════════
        // ENTITY TESTS
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC1: Single operand entity construction.
        /// </summary>
        [TestMethod]
        public void TestEntity_SingleOperandConstruction()
        {
            var entity = new QuantityMeasurementEntity(
                "1 FEET",
                QuantityMeasurementEntity.Operations.CONVERT,
                "12.00 INCHES"
            );

            Assert.AreEqual("1 FEET",   entity.FirstOperand);
            Assert.AreEqual(QuantityMeasurementEntity.Operations.CONVERT,
                            entity.OperationType);
            Assert.AreEqual("12.00 INCHES", entity.Result);
            Assert.IsFalse(entity.HasError);
        }

        /// <summary>
        /// TC2: Binary operand entity construction.
        /// </summary>
        [TestMethod]
        public void TestEntity_BinaryOperandConstruction()
        {
            var entity = new QuantityMeasurementEntity(
                "1 FEET",
                "12 INCHES",
                QuantityMeasurementEntity.Operations.ADD,
                "2.00 FEET",
                "LENGTH"
            );

            Assert.AreEqual("1 FEET",    entity.FirstOperand);
            Assert.AreEqual("12 INCHES", entity.SecondOperand);
            Assert.AreEqual(QuantityMeasurementEntity.Operations.ADD,
                            entity.OperationType);
            Assert.AreEqual("2.00 FEET", entity.Result);
            Assert.IsFalse(entity.HasError);
        }

        /// <summary>
        /// TC3: Error entity construction.
        /// </summary>
        [TestMethod]
        public void TestEntity_ErrorConstruction()
        {
            var entity = new QuantityMeasurementEntity(
                QuantityMeasurementEntity.Operations.ADD,
                "Temperature does not support arithmetic.",
                true
            );

            Assert.IsTrue(entity.HasError);
            Assert.AreEqual(
                "Temperature does not support arithmetic.",
                entity.ErrorMessage
            );
        }

        /// <summary>
        /// TC4: Entity ID is auto generated and not null.
        /// </summary>
        [TestMethod]
        public void TestEntity_IdAutoGenerated()
        {
            var entity = new QuantityMeasurementEntity(
                "1 FEET",
                QuantityMeasurementEntity.Operations.CONVERT,
                "12.00 INCHES"
            );

            Assert.IsNotNull(entity.Id);
            Assert.AreNotEqual(string.Empty, entity.Id);
        }

        // ═════════════════════════════════════════════════════
        // EXCEPTION TESTS
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC5: Exception stores correct error code.
        /// </summary>
        [TestMethod]
        public void TestException_ErrorCodeStored()
        {
            var ex = new QuantityMeasurementException(
                "Invalid unit",
                QuantityMeasurementException.ErrorCodes.INVALID_UNIT
            );

            Assert.AreEqual(
                QuantityMeasurementException.ErrorCodes.INVALID_UNIT,
                ex.ErrorCode
            );
            Assert.AreEqual("Invalid unit", ex.Message);
        }

        /// <summary>
        /// TC6: Exception with inner exception.
        /// </summary>
        [TestMethod]
        public void TestException_InnerException()
        {
            var inner = new ArgumentException("bad argument");

            var ex = new QuantityMeasurementException(
                "Wrapped error",
                QuantityMeasurementException.ErrorCodes.INVALID_VALUE,
                inner
            );

            Assert.AreEqual(inner, ex.InnerException);
        }

        // ═════════════════════════════════════════════════════
        // REPOSITORY TESTS
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC7: Repository saves and retrieves entity.
        /// </summary>
        [TestMethod]
        public void TestRepository_SaveAndRetrieve()
        {
            var entity = new QuantityMeasurementEntity(
                "1 FEET",
                QuantityMeasurementEntity.Operations.CONVERT,
                "12.00 INCHES"
            );

            _repository.Save(entity);
            var all = _repository.GetAllMeasurements();

            Assert.AreEqual(1,         all.Count);
            Assert.AreEqual(entity.Id, all[0].Id);
        }

        /// <summary>
        /// TC8: Repository FindById returns correct entity.
        /// </summary>
        [TestMethod]
        public void TestRepository_FindById()
        {
            var entity = new QuantityMeasurementEntity(
                "1 FEET",
                QuantityMeasurementEntity.Operations.CONVERT,
                "12.00 INCHES"
            );
            _repository.Save(entity);

            var found = _repository.FindById(entity.Id);

            Assert.IsNotNull(found);
            Assert.AreEqual(entity.Id, found!.Id);
        }

        /// <summary>
        /// TC9: Repository DeleteById removes entity.
        /// </summary>
        [TestMethod]
        public void TestRepository_DeleteById()
        {
            var entity = new QuantityMeasurementEntity(
                "1 FEET",
                QuantityMeasurementEntity.Operations.CONVERT,
                "12.00 INCHES"
            );
            _repository.Save(entity);

            _repository.DeleteById(entity.Id);

            Assert.AreEqual(0, _repository.GetAllMeasurements().Count);
        }

        /// <summary>
        /// TC10: Repository ClearAll removes all entities.
        /// </summary>
        [TestMethod]
        public void TestRepository_ClearAll()
        {
            _repository.Save(new QuantityMeasurementEntity(
                "1 FEET",
                QuantityMeasurementEntity.Operations.CONVERT,
                "12.00 INCHES"
            ));
            _repository.Save(new QuantityMeasurementEntity(
                "1 KG",
                QuantityMeasurementEntity.Operations.CONVERT,
                "1000.00 GRAM"
            ));

            _repository.ClearAll();

            Assert.AreEqual(0, _repository.GetAllMeasurements().Count);
        }

        // ═════════════════════════════════════════════════════
        // SERVICE - COMPARE TESTS
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC11: Compare equal lengths returns true.
        /// </summary>
        [TestMethod]
        public void TestService_Compare_EqualLengths_ReturnsTrue()
        {
            var first  = new QuantityDTO(1,  LengthUnitDTO.FEET,
                             MeasurementTypeDTO.LENGTH);
            var second = new QuantityDTO(12, LengthUnitDTO.INCHES,
                             MeasurementTypeDTO.LENGTH);

            var result = _service.Compare(first, second);

            Assert.AreEqual("True", result.Unit);
        }

        /// <summary>
        /// TC12: Compare unequal lengths returns false.
        /// </summary>
        [TestMethod]
        public void TestService_Compare_UnequalLengths_ReturnsFalse()
        {
            var first  = new QuantityDTO(1, LengthUnitDTO.FEET,
                             MeasurementTypeDTO.LENGTH);
            var second = new QuantityDTO(5, LengthUnitDTO.INCHES,
                             MeasurementTypeDTO.LENGTH);

            var result = _service.Compare(first, second);

            Assert.AreEqual("False", result.Unit);
        }

        /// <summary>
        /// TC13: Compare cross category throws exception.
        /// </summary>
        [TestMethod]
        public void TestService_Compare_CrossCategory_ThrowsException()
        {
            var first  = new QuantityDTO(1, LengthUnitDTO.FEET,
                             MeasurementTypeDTO.LENGTH);
            var second = new QuantityDTO(1, WeightUnitDTO.KILOGRAM,
                             MeasurementTypeDTO.WEIGHT);

            try
            {
                _service.Compare(first, second);
                Assert.Fail("Expected QuantityMeasurementException.");
            }
            catch (QuantityMeasurementException)
            {
                
            }
        }

        // ═════════════════════════════════════════════════════
        // SERVICE - CONVERT TESTS
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC14: Convert 1 feet to 12 inches.
        /// </summary>
        [TestMethod]
        public void TestService_Convert_FeetToInches()
        {
            var quantity = new QuantityDTO(1, LengthUnitDTO.FEET,
                               MeasurementTypeDTO.LENGTH);

            var result = _service.Convert(quantity, LengthUnitDTO.INCHES);

            Assert.AreEqual(12.0, result.Value, 0.0001);
            Assert.AreEqual(LengthUnitDTO.INCHES, result.Unit);
        }

        /// <summary>
        /// TC15: Convert 1 kg to 1000 grams.
        /// </summary>
        [TestMethod]
        public void TestService_Convert_KgToGrams()
        {
            var quantity = new QuantityDTO(1, WeightUnitDTO.KILOGRAM,
                               MeasurementTypeDTO.WEIGHT);

            var result = _service.Convert(quantity, WeightUnitDTO.GRAM);

            Assert.AreEqual(1000.0, result.Value, 0.0001);
        }

        /// <summary>
        /// TC16: Convert Celsius to Fahrenheit.
        /// </summary>
        [TestMethod]
        public void TestService_Convert_CelsiusToFahrenheit()
        {
            var quantity = new QuantityDTO(100,
                               TemperatureUnitDTO.CELSIUS,
                               MeasurementTypeDTO.TEMPERATURE);

            var result = _service.Convert(quantity,
                             TemperatureUnitDTO.FAHRENHEIT);

            Assert.AreEqual(212.0, result.Value, 0.0001);
        }

        // ═════════════════════════════════════════════════════
        // SERVICE - ADD TESTS
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC17: Add 1 feet + 12 inches = 2 feet.
        /// </summary>
        [TestMethod]
        public void TestService_Add_FeetAndInches_ReturnsFeet()
        {
            var first  = new QuantityDTO(1,  LengthUnitDTO.FEET,
                             MeasurementTypeDTO.LENGTH);
            var second = new QuantityDTO(12, LengthUnitDTO.INCHES,
                             MeasurementTypeDTO.LENGTH);

            var result = _service.Add(first, second);

            Assert.AreEqual(2.0, result.Value, 0.0001);
            Assert.AreEqual(LengthUnitDTO.FEET, result.Unit);
        }

        /// <summary>
        /// TC18: Add with explicit target unit.
        /// </summary>
        [TestMethod]
        public void TestService_Add_WithTargetUnit_ReturnsInches()
        {
            var first  = new QuantityDTO(1, LengthUnitDTO.FEET,
                             MeasurementTypeDTO.LENGTH);
            var second = new QuantityDTO(6, LengthUnitDTO.INCHES,
                             MeasurementTypeDTO.LENGTH);

            var result = _service.Add(first, second, LengthUnitDTO.INCHES);

            Assert.AreEqual(18.0, result.Value, 0.0001);
            Assert.AreEqual(LengthUnitDTO.INCHES, result.Unit);
        }

        /// <summary>
        /// TC19: Add temperature throws exception.
        /// </summary>
        [TestMethod]
        public void TestService_Add_Temperature_ThrowsException()
        {
            var first  = new QuantityDTO(100,
                             TemperatureUnitDTO.CELSIUS,
                             MeasurementTypeDTO.TEMPERATURE);
            var second = new QuantityDTO(50,
                             TemperatureUnitDTO.CELSIUS,
                             MeasurementTypeDTO.TEMPERATURE);

            try
            {
                _service.Add(first, second);
                Assert.Fail("Expected QuantityMeasurementException.");
            }
            catch (QuantityMeasurementException)
            {
                
            }
        }

        // ═════════════════════════════════════════════════════
        // SERVICE - SUBTRACT TESTS
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC20: Subtract 500g from 1kg = 0.5 kg.
        /// </summary>
        [TestMethod]
        public void TestService_Subtract_KgAndGrams()
        {
            var first  = new QuantityDTO(1,   WeightUnitDTO.KILOGRAM,
                             MeasurementTypeDTO.WEIGHT);
            var second = new QuantityDTO(500, WeightUnitDTO.GRAM,
                             MeasurementTypeDTO.WEIGHT);

            var result = _service.Subtract(first, second);

            Assert.AreEqual(0.5, result.Value, 0.0001);
        }

        // ═════════════════════════════════════════════════════
        // SERVICE - DIVIDE TESTS
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC21: Divide 2 gallons by 1 gallon = 2.
        /// </summary>
        [TestMethod]
        public void TestService_Divide_GallonByGallon()
        {
            var first  = new QuantityDTO(2, VolumeUnitDTO.GALLON,
                             MeasurementTypeDTO.VOLUME);
            var second = new QuantityDTO(1, VolumeUnitDTO.GALLON,
                             MeasurementTypeDTO.VOLUME);

            var result = _service.Divide(first, second);

            Assert.AreEqual(2.0, result.Value, 0.0001);
        }

        /// <summary>
        /// TC22: Divide by zero throws exception.
        /// </summary>
        [TestMethod]
        public void TestService_Divide_ByZero_ThrowsException()
        {
            var first  = new QuantityDTO(2, LengthUnitDTO.FEET,
                             MeasurementTypeDTO.LENGTH);
            var second = new QuantityDTO(0, LengthUnitDTO.FEET,
                             MeasurementTypeDTO.LENGTH);

            try
            {
                _service.Divide(first, second);
                Assert.Fail("Expected QuantityMeasurementException.");
            }
            catch (QuantityMeasurementException)
            {
                
            }
        }

        // ═════════════════════════════════════════════════════
        // NULL VALIDATION TESTS
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC23: Null first quantity throws exception.
        /// </summary>
        [TestMethod]
        public void TestService_NullFirstQuantity_ThrowsException()
        {
            var second = new QuantityDTO(1, LengthUnitDTO.FEET,
                             MeasurementTypeDTO.LENGTH);

            try
            {
                _service.Compare(null!, second);
                Assert.Fail("Expected QuantityMeasurementException.");
            }
            catch (QuantityMeasurementException)
            {
                
            }
        }

        /// <summary>
        /// TC24: Null second quantity throws exception.
        /// </summary>
        [TestMethod]
        public void TestService_NullSecondQuantity_ThrowsException()
        {
            var first = new QuantityDTO(1, LengthUnitDTO.FEET,
                            MeasurementTypeDTO.LENGTH);

            try
            {
                _service.Compare(first, null!);
                Assert.Fail("Expected QuantityMeasurementException.");
            }
            catch (QuantityMeasurementException)
            {
                
            }
        }

        // ═════════════════════════════════════════════════════
        // REPOSITORY SAVES AFTER EACH OPERATION
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC25: Repository saves record after compare.
        /// </summary>
        [TestMethod]
        public void TestRepository_SavesAfterCompare()
        {
            var first  = new QuantityDTO(1,  LengthUnitDTO.FEET,
                             MeasurementTypeDTO.LENGTH);
            var second = new QuantityDTO(12, LengthUnitDTO.INCHES,
                             MeasurementTypeDTO.LENGTH);

            _service.Compare(first, second);

            Assert.AreEqual(1, _repository.GetAllMeasurements().Count);
        }

        /// <summary>
        /// TC26: Repository saves record after convert.
        /// </summary>
        [TestMethod]
        public void TestRepository_SavesAfterConvert()
        {
            var quantity = new QuantityDTO(1, LengthUnitDTO.FEET,
                               MeasurementTypeDTO.LENGTH);

            _service.Convert(quantity, LengthUnitDTO.INCHES);

            Assert.AreEqual(1, _repository.GetAllMeasurements().Count);
        }

        // ═════════════════════════════════════════════════════
        // SINGLETON TEST
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC27: Repository singleton returns same instance.
        /// </summary>
        [TestMethod]
        public void TestRepository_Singleton_SameInstance()
        {
            var instance1 = QuantityMeasurementCacheRepository.GetInstance();
            var instance2 = QuantityMeasurementCacheRepository.GetInstance();

            Assert.AreSame(instance1, instance2);
        }

        // ═════════════════════════════════════════════════════
        // DTO AND MODEL TESTS
        // ═════════════════════════════════════════════════════

        /// <summary>
        /// TC28: QuantityDTO stores values correctly.
        /// </summary>
        [TestMethod]
        public void TestDTO_StoresValuesCorrectly()
        {
            var dto = new QuantityDTO(10,
                          LengthUnitDTO.FEET,
                          MeasurementTypeDTO.LENGTH);

            Assert.AreEqual(10,                      dto.Value);
            Assert.AreEqual(LengthUnitDTO.FEET,      dto.Unit);
            Assert.AreEqual(MeasurementTypeDTO.LENGTH, dto.MeasurementType);
        }

        /// <summary>
        /// TC29: QuantityModel stores values correctly.
        /// </summary>
        [TestMethod]
        public void TestModel_StoresValuesCorrectly()
        {
            var model = new QuantityModel(10,
                            LengthUnitDTO.FEET,
                            MeasurementTypeDTO.LENGTH);

            Assert.AreEqual(10,                        model.Value);
            Assert.AreEqual(LengthUnitDTO.FEET,        model.Unit);
            Assert.AreEqual(MeasurementTypeDTO.LENGTH,  model.MeasurementType);
        }
    }
}